
version: '3'
services:

  bot:
    build: ./bot
    env_file:
      - env/avibot.env
      - env/postgres.env
    volumes: 
      - ./bot:/bot
    command: [ "python", "launcher.py"]

  postgres:
    image: postgres:latest
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
